---
- name: "PLAY 0: Gather all the required info from the user."
  vars_prompt:
    - name: "menumuser"
      prompt: "Enter the ME number (e.g. 2)"
      private: no
    - name: "ximnumuser"
      prompt: "Enter the XIM number (e.g. 2)"
      private: no
    - name: "missionnumuser"
      prompt: "Enter the mission number (e.g. WC-1000-19)"
      private: no
    - name: "tunnelnumuser"
      prompt: "Enter Tunnel Number (e.g. 9152)"
      private: no
    - name: "tunnelipuser"
      prompt: "Enter RHN Tunnel IP"
      private: no
    - name: "tunnelmaskuser"
      prompt: "Enter Tunnel Subnet Mask"
      private: no
    - name: "tunnelsourceuser"
      prompt: "Enter RHN Tunnel Source Interface IP address"
      private: no
    - name: "tunnelsourcemaskuser"
      prompt: "Enter RHN Tunnel Source Interface Mask"
      private: no
    - name: "nhrpauthuser"
      prompt: "Enter IP NHRP Authentication (e.g. 22196780)"
      private: no
    - name: "nhrpiduser"
      prompt: "Enter NHRP ID and Tunnel Key (e.g. 96780)"
      private: no
  tasks:
    - set_fact:
        menum: "{{menumuser}}"
        ximnum: "{{ximnumuser}}"
        msnnum: "{{missionnumuser}}"
        tunnelnum: "{{ tunnelnumuser}}"
        tunnelip: "{{tunnelipuser}}"
        tunnelmask: "{{tunnelmaskuser}}"
        tunnelsource: "{{tunnelsourceuser}}"
        tunnelsourcemask: "{{tunnelsourcemaskuser}}"
        nhrpauth: "{{nhrpauthuser}}"
        nhrpid: "{{nhrpiduser}}"
  hosts: localhost

- name: "Role 1: Add Inc1 Tunnel Configuration to Router"
  hosts: "me{{ hostvars['localhost']['menum'] }}"
  roles:
    - add-inc1-tunnel

- name: "Role 2: Add Subinterface to Router"
  hosts: "me{{ hostvars['localhost']['menum'] }}"
  roles:
    - add-router-subinterface

- name: "Role 3: Add configuration to XIMs Switch"
  hosts: "xim{{hostvars['localhost']['ximnum']}}"
  roles:
    - add-xims-interface-config
