---
all:
  vars:
    #network_cli
    ansible_network_os: ios
    ansible_user: "ansible"
    ansible_password: "ansible"
me1:
  hosts:
    ec2-100-24-106-233.compute-1.amazonaws.com:
me2:
  hosts:
    ec2-18-204-44-222.compute-1.amazonaws.com:
