---
- name: "PLAY 1: Get all the variables and input a valid tunnel config"
  vars_prompt:
    - name: "me_num"
      prompt: "Enter the ME number (e.g. 2)"
      private: no
    - name: "mission_num"
      prompt: "Enter the mission number (e.g. WC-1000-19)"
      private: no
    - name: "tunnel_num"
      prompt: "Enter Tunnel Number (e.g. 96780)"
      private: no
    - name: "tunnel_ip"
      prompt: "Enter RHN Tunnel IP"
      private: no
    - name: "tunnel_mask"
      prompt: "Enter Tunnel Subnet Mask"
      private: no
    - name: "nhrp_auth"
      prompt: "Enter IP NHRP Authentication (e.g. 22196780)"
      private: no
    - name: "nhrp_id"
      prompt: "Enter NHRP ID and Tunnel Key (e.g 96780)"
      private: no
    - name: "tunnel_source"
      prompt: "Enter RHN Tunnel Source IP"
      private: no
  hosts: "me{{ me_num }}"
  tasks:
    - name: "TASK 0: Input Tunnel Config into Router"
      ios_config:
        lines:
          - "interface Tunnel{{ tunnel_num }}"
          - "description DMVPN Tunnel for {{ mission_num }}"
          - "bandwidth 6144"
          - "ip address {{ tunnel_ip }} {{ tunnel_mask }}"
          - "no ip redirects"
          - "no ip unreachables"
          - "ip mtu 1420"
          - "ip pim nbma-mode"
          - "ip pim sparse-mode"
          - "ip nhrp map multicast dynamic"
          - "ip nhrp authentication {{ nhrp_auth }}"
          - "ip nhrp network-id {{ nhrp_id }}"
          - "ip nhrp holdtime 600"
          - "ipv6 address FC00::{{ tunnel_ip }}/122"
          - "ipv6 mtu 1420"
          - "ipv6 nhrp map multicast dynamic"
          - "ipv6 nhrp authentication {{ nhrp_auth }}"
          - "ipv6 nhrp network-id {{ nhrp_id }}"
          - "ipv6 nhrp holdtime 600"
          - "ip tcp adjust-mss 1332"
          - "ospfv3 2 network broadcast"
          - "ospfv3 2 priority 5"
          - "ospfv3 2 flood-reduction"
          - "ospfv3 2 cost 12400"
          - "ospfv3 2 area 0 ipv4"
          - "tunnel source {{ tunnel_source }}"
          - "tunnel key {{ nhrp_id }}"
          - "tunnel mode gre multipoint"
          - "tunnel protection ipsec profile colorless"
