- name: "Role: Input an Inc1 tunnel configuration into Router"
  ios_config:
    lines:
      - "description DMVPN Tunnel for {{ hostvars['localhost']['tunnelnum'] }}"
      - "bandwidth 6144"
      - "ip address {{ hostvars['localhost']['tunnelip'] }} {{ hostvars['localhost']['tunnelmask'] }}"
      - "no ip redirects"
      - "no ip unreachables"
      - "ip mtu 1420"
      - "ip pim nbma-mode"
      - "ip pim sparse-mode"
      - "ip nhrp map multicast dynamic"
      - "ip nhrp authentication {{ hostvars['localhost']['nhrpauth'] }}"
      - "ip nhrp network-id {{ hostvars['localhost']['nhrpid'] }}"
      - "ip nhrp holdtime 600"
      - "ipv6 address FC00::{{ hostvars['localhost']['tunnelip'] }}/122"
      - "ipv6 mtu 1420"
      - "ipv6 nhrp map multicast dynamic"
      - "ipv6 nhrp authentication {{ hostvars['localhost']['nhrpauth'] }}"
      - "ipv6 nhrp network-id {{ hostvars['localhost']['nhrpid'] }}"
      - "ipv6 nhrp holdtime 600"
      - "ip tcp adjust-mss 1332"
      - "ospfv3 2 network broadcast"
      - "ospfv3 2 priority 5"
      - "ospfv3 2 flood-reduction"
      - "ospfv3 2 cost 12400"
      - "ospfv3 2 area 0 ipv4"
      # Interface below needs changed to "g3." in production
      - "tunnel source e1/0.{{ hostvars['localhost']['tunnelnum'][1:] }}"
      - "tunnel key {{ hostvars['localhost']['nhrpid'] }}"
      - "tunnel mode gre multipoint"
      - "tunnel protection ipsec profile colorless"
    parents: "interface Tunnel{{ hostvars['localhost']['tunnelnum'] }}"
